# Generated by Django 4.2.2 on 2023-06-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_online_user_customer_staff_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='online_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='staff_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='', upload_to='customer_photos'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', '客戶'), ('employee', '員工'), ('manager', '主管')], default='customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
